print('hello')
print("hello")
print("this is also a string")
print("I'm going on a run")
print("Hello world 1")
print("Hello world 2")
print("Hello \nworld 2")
print("Hello \tworld 2")
print(len("Hello \tworld 2"))